=== tan951/Document-Digitizer-System/packages/preprocess/schemas/preprocess.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Module1Output",
  "type": "object",
  "required": ["request_id","document_id","module","version","timestamp","status","payload"],
  "properties": {
    "request_id": { "type": "string" },
    "document_id": { "type": "string" },
    "module": { "type": "string" },
    "version": { "type": "string" },
    "timestamp": { "type": "string" },
    "status": { "type": "string", "enum": ["success", "error"] },
    "error": {
      "type": ["object", "null"],
      "properties": {
        "code": { "type": "string" },
        "message": { "type": "string" }
      },
      "required": ["code", "message"]
    },
    "payload": {
      "type": "object",
      "required": ["page","input_image","output_image","width","height","rotation","is_blank"],
      "properties": {
        "page": { "type": "integer" },
        "input_image": { "type": "string" },
        "output_image": { "type": "string" },
        "width": { "type": "integer" },
        "height": { "type": "integer" },
        "rotation": { "type": "integer" },
        "is_blank": { "type": "boolean" },
        "blank_ratio": { "type": "number" },
        "crop_applied": { "type": "boolean" },
        "deskew_angle": { "type": "number" },
        "osd": { "type": ["object","null"] }
      }
    }
  }
}

=== tan951/Document-Digitizer-System/packages/preprocess/data/json/test2.json
{
  "request_id": "d29f77c1-0199-4894-b75f-07d9fe17c320",
  "document_id": "local_doc_6",
  "module": "preprocess",
  "version": "1.0.0",
  "timestamp": "2026-04-29T06:39:43.662191Z",
  "status": "success",
  "error": null,
  "payload": {
    "page": 6,
    "input_image": "data\\input\\test2.jpg",
    "output_image": "data\\output\\test2_clean.png",
    "width": 1920,
    "height": 2560,
    "rotation": 0,
    "is_blank": false,
    "blank_ratio": 0.1477862548828125,
    "crop_applied": false,
    "deskew_angle": -0.0,
    "osd": {
      "attempted": true,
      "success": false,
      "message": "(1, 'Estimating resolution as 338 Warning. Invalid resolution 0 dpi. Using 70 instead. Too few characters. Skipping this page Error during processing.')"
    }
  }
}

=== tan951/Document-Digitizer-System/packages/preprocess/data/json/20140603_0003_BCCTC_tg_0_2.json
{
  "request_id": "54631ead-b055-4cbf-84c4-2cb1efff7b7f",
  "document_id": "local_doc_3",
  "module": "preprocess",
  "version": "1.0.0",
  "timestamp": "2026-04-29T06:39:37.153812Z",
  "status": "success",
  "error": null,
  "payload": {
    "page": 3,
    "input_image": "data\\input\\20140603_0003_BCCTC_tg_0_2.png",
    "output_image": "data\\output\\20140603_0003_BCCTC_tg_0_2_clean.png",
    "width": 515,
    "height": 54,
    "rotation": 0,
    "is_blank": false,
    "blank_ratio": 0.05127651923768429,
    "crop_applied": false,
    "deskew_angle": 2.256793975830078,
    "osd": {
      "attempted": false,
      "success": false,
      "message": ""
    }
  }
}

=== tan951/Document-Digitizer-System/packages/preprocess/data/json/test1.json
{
  "request_id": "2778124e-9b96-4c0b-b97a-9c8d0978e4c4",
  "document_id": "local_doc_5",
  "module": "preprocess",
  "version": "1.0.0",
  "timestamp": "2026-04-29T06:39:40.394999Z",
  "status": "success",
  "error": null,
  "payload": {
    "page": 5,
    "input_image": "data\\input\\test1.jpg",
    "output_image": "data\\output\\test1_clean.png",
    "width": 2560,
    "height": 1920,
    "rotation": 270,
    "is_blank": false,
    "blank_ratio": 0.06823710123697917,
    "crop_applied": false,
    "deskew_angle": -0.0,
    "osd": {
      "attempted": true,
      "success": true,
      "message": ""
    }
  }
}
